[package]
name = "blog_chk"
version = "0.1.0"
edition = "2021"

[lib]
name = "blog_chk"
path = "src/lib.rs"

[dependencies]

[dependencies.blog_err]
path = "../blog_err"

[dependencies.blog_prs]
path = "../blog_prs"
