[package]
name = "blog_str"
version = "0.1.0"
edition = "2021"

[dependencies]
pathdiff = "0.2.1"
walkdir = "2.5.0"

[dependencies.blog_cfg]
path = "../blog_cfg"

[dependencies.blog_env]
path = "../blog_env"

[dependencies.blog_err]
path = "../blog_err"

[dependencies.blog_grt]
path = "../blog_grt"